name: CI/CD Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      # 2a. Branch Dev: build
      - name: Build Check (Dev Branch)
        if: github.ref == 'refs/heads/dev'
        run: mvn clean compile -DskipTests

      # 2b. Branch Main: build + push docker
      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Native Image (Buildpacks)
        if: github.ref == 'refs/heads/main'
        run: |
          mvn -DskipTests spring-boot:build-image \
            -Dspring-boot.build-image.imageName=${{ secrets.DOCKER_USERNAME }}/pingme-core-service:native-${{ github.run_number }} \
            -Dspring-boot.build-image.publish=true \
            -Dspring-boot.build-image.environment.BP_NATIVE_IMAGE=true

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Generate Dockerrun.aws.json
        run: |
          cat > Dockerrun.aws.json <<EOF
          {
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "${{ secrets.DOCKER_USERNAME }}/pingme-core-service:native-${{ github.run_number }}",
              "Update": "true"
            },
            "Ports": [
              {
                "ContainerPort": "8080"
              }
            ]
          }
          EOF

      - name: Zip Dockerrun.aws.json
        run: zip -r deploy.zip Dockerrun.aws.json

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: PingMe
          environment_name: PingMe-env
          version_label: v-${{ github.run_id }}-${{ github.run_attempt }}
          region: ap-southeast-1
          deployment_package: deploy.zip

